- name: Variables
  hosts: localhost
  vars:  #to declare variables
    Movie: "The Odyssey"
    Loc: "AAAs Hyderabad"
    Duration: "3hrs"
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "We are going to watch movie {{Movie}} in {{Loc}},with duration about {{Duration}}."