- name: Loops in YAML
  hosts: web
  become: yes 
  tasks:
    - name: printing with Loops
      ansible.builtin.debug:
        msg: "Hello {{ item }}"
      loop:
        - linux
        - shell
        - ansible
