- name: play1 & task1
  hosts: web
  become: yes
  tasks: 
   - name: task1 & play1
     ansible.builtin.debug:
       msg: "Hi,Hello from play1 & task1"

- name: play2 & task2
  hosts: web
  become: yes
  tasks: 
    - name: task2 & play2
      ansible.builtin.debug:
        msg: "Hi,Hello from play2 & task2"