- name: vars by prompts
  hosts: web
  become: yes
  vars_prompt:
    - name: username
      prompt: "Please enter your username"
      private: false
    - name: password
      prompt: "Enter your password"
      private: true
  tasks:
    - name: print info
      ansible.builtin.debug:
        msg: "Hi, this is {{username}} and the password is {{password}}"
